DROP DATABASE IF EXISTS banco;

CREATE DATABASE banco;

USE banco;

CREATE TABLE usuarios(
    IdPer VARCHAR(10) NOT NULL,
    NomPer VARCHAR(255) NOT NULL,
    NumCue BIGINT(255) UNSIGNED NOT NULL,
    CupCre VARCHAR(255) NOT NULL,
    TelUsu VARCHAR(10) NOT NULL,
    DirUsu VARCHAR(10) NOT NULL,
    PasUsu VARCHAR(255) NOT NULL,
  PRIMARY KEY (IdPer)
);